apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: prometheus-demo
    monitoring: devfest-monitoring
  name: prometheus-demo
  namespace: devfest
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prometheus-demo
      monitoring: devfest-monitoring
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: prometheus-demo
        monitoring: devfest-monitoring
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'actuator/prometheus'
        prometheus.io/port: '8080'
    spec:
      containers:
      - image: gcr.io/inspired-bus-194216/springboot-prometheus
        name: prometheus-demo
        ports:
        - containerPort: 8080
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    monitoring: devfest-monitoring
    run: prometheus-demo
  name: prometheus-demo
  namespace: devfest
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    monitoring: devfest-monitoring
    run: prometheus-demo
  type: ClusterIP
status:
  loadBalancer: {}
