apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      monitoring: devfest-monitoring
      run: prometheus-demo
    name: prometheus-demo
    namespace: dev-fest
  spec:
    progressDeadlineSeconds: 600
    replicas: 5
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        monitoring: devfest-monitoring
        run: prometheus-demo
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          monitoring: devfest-monitoring
          run: prometheus-demo
      spec:
        containers:
        - image: gcr.io/inspired-bus-194216/springboot-prometheus
          imagePullPolicy: Always
          name: prometheus-demo
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 5
    conditions:
    - lastTransitionTime: 2018-11-03T12:13:05Z
      lastUpdateTime: 2018-11-03T12:13:12Z
      message: ReplicaSet "prometheus-demo-6849f458fd" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: 2018-11-03T12:54:52Z
      lastUpdateTime: 2018-11-03T12:54:52Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 3
    readyReplicas: 5
    replicas: 5
    updatedReplicas: 5
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
