apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: spring-demo
    prometheus: spring-demo
  name: spring-demo-app
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    path: /actuator/prometheus
    port: http
  jobLabel: spring-demo-app
  namespaceSelector:
    matchNames:
    - platform
  selector:
    matchLabels:
      monitoring: device-mapper 
